### ISSUE TITLE
Feature Request: Window Highlighting?

### ISSUE THREAD

**Issue by ParasiteDelta** [glazerdesktop/GlazeWM#100]
I know that this is probably difficult, clunky, or impossible given Windows and its shell, but I was wondering if it _might_ be possible to create a border highlight for the currently-selected window in the same vein as i3, showing which window you currently have selected. While you kind of can tell which is selected if you look, there's no current way to just look across your screen and be able to tell which window is currently active, which can hinder productivity in keyboard-only solutions.

Just a thought.

**Comment by lars-berger** [comment]
It's possible and it's a feature in [Workspacer ](https://github.com/workspacer/workspacer)(an alternative WM for Windows). However, the downside is that there's a very noticeable delay for the highlight border to move around. Essentially, a rectangle is drawn around the window and is moved around on window move, resize, and focus change.

An alternative approach is to somehow make window borders thicker natively. There's mentions of a registry key that you used to be able to change at `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics` for `BorderWidth` and `PaddedBorderWidth`, but this seems to only change the size of the title bar now (and only for certain windows).

As it stands right now, I don't know a good way to implement this. Will definitely leave this open though in case someone knows another way that this could be added.

**Comment by es183923** [comment]
The window border lag is an issue in komorebi (another WM for windows), and yabai (WM for macOS). I don't think that its a particularly big issue, and there doesn't seem to be a better way. 

I don't think using a native method would work, considering how many of the APIs may be inconsistent, and some windows just aren't able to be modified through normal API calls.

**Comment by lars-berger** [comment]
@es183923 You're probably right, but I still have a little bit of hope that there's some way to do this natively. For example, there's a Reddit thread [here](https://www.reddit.com/r/Windows11/comments/ouc2vm/window_borders_in_windows_11/) where someone posted a W11 desktop with some very thick borders.

**Comment by es183923** [comment]
Edge and Calculator don't seem to have the same result as the other apps with the titlebar not being the same color, and all of them seem to be native Windows apps. I don't think that this way would work with every single app.

**Comment by Fuann-Kinoko** [comment]
I saw [this](https://www.reddit.com/r/windowsporn/comments/x6299x/a_small_effect_on_window_switching/) ahk script on reddit, and it should work for you after removing the last few lines. Note that this script seems to have some problems with maximized windows.
