### ISSUE TITLE
Feature request: winget installer

### ISSUE THREAD

**Issue by al3xfischer** [glazerdesktop/GlazeWM#170]
I would appreciate it if the GlazeWM could be installed via winget.

https://learn.microsoft.com/en-us/windows/package-manager/package/

**Comment by afermar** [comment]
I made a [PR](https://github.com/microsoft/winget-pkgs/pull/89343) to include GlazeWM in [winget-pkgs](https://github.com/microsoft/winget-pkgs). It has been approved and merged, so it should be available to install via winget shortly.

For future releases maybe something like [winget-releaser](https://github.com/marketplace/actions/winget-releaser) could be implemented to automate the process. @lars-berger

**Comment by lars-berger** [comment]
@afermar That's awesome, thank you so much ❤️ I'll give it a try tonight and add a little section to the readme for winget installations
