### ISSUE TITLE
Feature Request: Check for updates

### ISSUE THREAD

**Issue by al1-ce** [glazerdesktop/GlazeWM#171]
Speaks for itself

Maybe check on launch and prompt if new version is available

**Comment by notblam** [comment]
If we primarily used scoop as an installer, I think we could rely on the package manager to perform updates.  Maybe when an update is installed, a browser window will launch to the github page displaying the patch notes.  We have to get a little more experience with installers/package managers first, but this is a goal of ours.  

So far I am a little torn between scoop and winget.
