### ISSUE TITLE
windows created by WSL2 don't work

### ISSUE THREAD

**Issue by lucvlaming** [glazerdesktop/GlazeWM#307]
i'm running intellij via debian on WSL2. whenever glazewm is active, the contents of the intellij windows won't show. when i exit glazewm and then start intellij it all works. 

i tried adding those windows to the "ignore" part, but somehow i can't seem to make that work either.

any suggestions?

**Comment by lucvlaming** [comment]
i tried now running with x410 (https://x410.dev/) and that at least works (compared to the normal RDP based approach). however the windows are still not managed.

**Comment by nvrprfct** [comment]
running glazewm as administrator?

**Comment by lucvlaming** [comment]
i tried both. neither helped much :(

**Comment by HolbyFPV** [comment]
Duplicate of #44.  

Closing this to keep all the discussion in one place.
