### ISSUE TITLE
Separate properties for horizontal and vertical outer_gap?

### ISSUE THREAD

**Issue by parsiad** [glazerdesktop/GlazeWM#313]
Hi,

Is it possible to implement separate properties for horizontal and vertical outer_gap? I would like to have a very large horizontal (left/right) outer_gap and a small vertical (top/bottom) outer_gap.

Thanks!

**Comment by maxle5** [comment]
[This PR](https://github.com/lars-berger/GlazeWM/pull/282) does what you're looking for, just needs to be reviewed and merged.

If approved, you would configure left and right outer gaps like this:
```
gaps:
  # Gap between windows and the screen edge. See "Shorthand properties" for more info.
  outer_gap: "0 200px 0 200px"
```
