### ISSUE TITLE
Feature Request: Add an option to add a border to the active window

### ISSUE THREAD

**Issue by Cornelius-Figgle** [glazerdesktop/GlazeWM#335]
Similar in visuals to [PowerToys always on top border](https://learn.microsoft.com/en-us/windows/images/pt-always-on-top.png) but for the active window

When the taskbar is hidden there isn't really a way to tell which window is currently activated (other than the title in the bar), and I think a border on the window would be an easy way of doing this

*[Hyprland also does this by default](https://repository-images.githubusercontent.com/643884298/45374c99-e991-40da-8a67-8baf4479ae6c)*

**Comment by Sinrefvol** [comment]
Hello! While this is not implemented, i recommend installing AutoHotkey v2 and running the following script to add that functionallity in meanwhile: [AHK script](https://gist.github.com/ericreeves/fd426cc0457a5a47058e1ad1a29d9bd6?permalink_comment_id=4539159#gistcomment-4539159)

If detects windows and draws borders aroud them.

**Comment by Cornelius-Figgle** [comment]
Ah okay, I would prefer to do it natively but AHK works too (I already use it so that should be fairly easy to implement)

**Comment by Sinrefvol** [comment]
It looks like this is not the easiest thing to do on windows. [Komorebi](https://github.com/LGUG2Z/komorebi) does in natively, but does rather badly.

**Comment by Cornelius-Figgle** [comment]
Is it not possible to use the [Window Style](https://www.autohotkey.com/docs/v2/misc/Styles.htm) to set the border (then it won't be Windows version specific)?

I am on phone atm so cannot test this but looks like you should be able to apply a style to the active window from within AHK

**Comment by Sinrefvol** [comment]
After some look-around i found this [commit](https://github.com/lars-berger/GlazeWM/commit/728527227b512a6f14daaee98dc3546574766cda) in main branch. Looks like it should be working now, however not yet released.

**Comment by Cornelius-Figgle** [comment]
I wonder why this is W11 specific only? Seems odd being that PowerToys can do it fine...

I will try the AHK approach bc I'm running W10

**Comment by Cornelius-Figgle** [comment]
I might also test the native method (and build from source) to see if its truly W11 specific or if thats just based off something MS have said

**Comment by Sinrefvol** [comment]
This AHK forum [post](https://www.autohotkey.com/boards/viewtopic.php?p=491292&sid=fd3148dabb51df4c907637ebb3663b95#p491292) shows how to do it in windows 10. I have tried it myself, but was not satisfied with the result - windows 10 borders are 4px wide, so you have to play a bit with offsett to make them thinner.

To make things worse, you will have to manually filter out some windows that should not have borders - for example PowerToys Run. 

Reason for only windows 11 support is documented [here](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute). `DWMWA_BORDER_COLOR` value for `DwmSetWindowAttribute` function is  is supported starting with Windows 11 Build 22000.

**Comment by Cornelius-Figgle** [comment]
Ah okay, I will try `WinSetStyle` when I get a chance - presumably Glaze could add this manually? Like just draw a box at the window pos instead of doing it through Windows (as a fallback for Windows vers not supported by the built-in approach)

**Comment by Sinrefvol** [comment]
You might be interested in looking at this [AHK post](https://www.autohotkey.com/boards/viewtopic.php?t=73197).
With some modification, you might achieve what you want.

**Comment by notblam** [comment]
> I wonder why this is W11 specific only? Seems odd being that PowerToys can do it fine...
> 
> I will try the AHK approach bc I'm running W10

There is a native API introduced in W11 that allows us to easily support this.  The PowerToys implementation that other programs use is a rather hacky workaround in comparison.

**Comment by Cornelius-Figgle** [comment]
Would an option to choose between methods not be valid?

```yaml
border_style: "native"
border_style: "manual"
border_style: "none"
```

Something like the above?
