### ISSUE TITLE
no preview when using altsnap/altdrag to position window in layout

### ISSUE THREAD

**Issue by airtonix** [glazerdesktop/GlazeWM#368]
on linux with gnome-shell and popshell tiling window manager extension. you can drag a window around and you will get a preview of where you want the new window to  sit in the layout.

glaze gives me no such preview, which results in a fairly cumbersome experience.

**Comment by HolbyFPV** [comment]
Closing this to keep all discussion regarding altsnap/altdrag in a single place.  

Refer to #367
