### ISSUE TITLE
Workspace switch click event broken in Bar

### ISSUE THREAD

**Issue by rootix** [glazerdesktop/GlazeWM#391]
Either PR #384 or #388 introduced the problem that a mouse click in the Bar on one of the Workspaces changes the window focus (Border goes away) but does not switch the workspace. The switch still works with the keybinds. I'm on commit add74f3

**Comment by Trevortds** [comment]
Also experiencing this. Compiled from source for the first time today to get the new bar utilities, clicking on the  workspaces widget in the bar only works sporadically. 

It seems to put keyboard focus on the first window in the selected workspace, but usually does not actually change the windows on screen. If a workspace has multiple windows in it, clicking on the widget will sometimes expose one of them, but not all of them. The click behavior seems dependent in some way on which workspace was selected with a keyboard binding last. 

I also compiled from add74f3.
