### ISSUE TITLE
Wacatac trojan

### ISSUE THREAD

**Issue by azinsharaf** [glazerdesktop/GlazeWM#408]
windows defender blocks the GalazeWM due to Wacatac trojan. Has anyone else seen this issue?

![image](https://github.com/glazerdesktop/GlazeWM/assets/10101468/5f983a5c-293a-425e-b80e-eb2bcc577c22)

**Comment by HolbyFPV** [comment]
This is the first we've seen this.  I assume you've downloaded from the releases page here on GitHub?  This is the only official release for the record.

**Comment by azinsharaf** [comment]
yes i've downloaded it from the Release page here.

**Comment by azinsharaf** [comment]
i am not getting the same warning for 2.0.1 version. I will let you know if it happens again for the new release. Closing the issue for now.
