### ISSUE TITLE
Focus commands not working when invoked through IPC

### ISSUE THREAD

**Issue by silvarc141** [glazerdesktop/GlazeWM#414]
# Problem
Focus commands not working properly when executed through IPC from command-line. Glaze behaves as if it changed focus while in reality it did not.

# Repro example:
1. Have Glaze running, a focused window (for example console) and another to the left
2. Execute `glazewm command \"""focus left\"""`
// Notice the window to the left should be focused but is not (typing still enters characters in the right window)
3. Execute `glazewm command \"""close\"""`
// The window to the left is correctly closed

**Comment by wis** [comment]
Does **any** IPC command work for you? none are having any effect for me, neither does `glazewm.exe command '"focus left"'` and neither does `glazewm.exe command '"focus workspace 1"'`

glazewm outputs the following when an IPC command is received, but nothing happens: 
```
11/20/2023 02:47:39[IpcMessageHandler] IPC message received: command "focus workspace 2".
11/20/2023 02:47:39[Bus] Command FocusWorkspaceCommand invoked.
11/20/2023 02:47:39[FocusWorkspaceHandler] WorkspaceToFocus: 2
11/20/2023 02:47:39[Bus] Command SetFocusedDescendantCommand invoked.
```

**Comment by silvarc141** [comment]
Did a re-check on develop, 454bc05cade0bc7eea4ffebd9af5c57dd87c85d3
OS: Windows 11

Commands that do not involve modifying/refreshing existing windows such as `close`, `exec` etc work correctly.

Commands that change windows but do not require focus (`toggle floating`, `toggle maximized`), do work, but the result is visible only after touching/moving the window manually, it does not refresh on its own.

Focus-related commands do not work through IPC.
GlazeWM state changes correctly, for example, workspace widget on status bar changes correctly when calling `glazewm command \"""focus workspace #\"""`, but other than that the command does nothing.
