### ISSUE TITLE
[question] having a clickable icon in `component center`

### ISSUE THREAD

**Issue by azinsharaf** [glazerdesktop/GlazeWM#440]
is there any way to have an icon `component_center` and use a left click event to run a command?
I'd like to have an application icon that opens an application when i click on it. I've tried `text_file` without luck,

**Comment by Lol-Lap** [comment]
> is there any way to have an icon `component_center` and use a left click event to run a command?
> I'd like to have an application icon that opens an application when i click on it. I've tried `text_file` without luck, 

![image-1.png](https://github.com/glazerdesktop/GlazeWM/assets/120711779/51a7337f-0fb9-4e9d-b4f2-b2fdd14673a7)

Try this i guess it still works.

**Comment by azinsharaf** [comment]
yes, it works. thanks!
