### ISSUE TITLE
VS Code unable to be put in tiling mode

### ISSUE THREAD

**Issue by JoeMesnard28** [glazerdesktop/GlazeWM#444]
Has anyone experienced the issue where VS code cannot be placed in tiling mode? It is always floating. This may be true of other windows too.

**Comment by UnknownRori** [comment]
Did you run VS Code in Adminstrator?

**Comment by JoeMesnard28** [comment]
Thanks for the response!

I am running VS Code as admin for development purposes. Does this app not support that? Is there some config I can change?

**Comment by UnknownRori** [comment]
From my experience I run GlazeWM in Administrator so other programs that run as Administrator also can be managed by GlazeWM, it is some sort of work around since I haven't found config to add or changes

**Comment by JoeMesnard28** [comment]
running glaze as admin works for me - thanks for the tip!!
