### ISSUE TITLE
"Snipaste" (a popular screenshot software) is not working properly on GlazeWM

### ISSUE THREAD

**Issue by daishengdong** [glazerdesktop/GlazeWM#457]
as stated in the title

**Comment by Fuann-Kinoko** [comment]
```
window_rules:
  - command: "ignore"
    match_process_name: "snipaste"
```

**Comment by daishengdong** [comment]
> ```
> window_rules:
>   - command: "ignore"
>     match_process_name: "snipaste"
> ```

it helps! thank you!

**Comment by HighLibrarian** [comment]
had the same issue with Lightshot and Pickpic. making a rule for them fixed it.
