### ISSUE TITLE
Any solution for PiP (Picture in Picture) ?

### ISSUE THREAD

**Issue by AmineDjeghri** [glazerdesktop/GlazeWM#479]
I use this feature specially on Youtube, but actiavting it makes the PiP window appear and is tilted. Is there any solution to keep the PiP window floating ?

**Comment by FrancisTheCat** [comment]
Its probably possible to add something to your config, that sets windows that have the title "Picture-in-Picture" to floating:
  - command: 'set floating'
    match_process_name: 'Picture-in-Picture'

**Comment by FrancisTheCat** [comment]
nvm its match_title just tested it

**Comment by b1scu1t** [comment]
I have used this rule for over 3 months, works for Firefox and (most?) Chromium-based browsers.
```
# Do not manage Picture-in-picture windows
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"
```

**Comment by melMass** [comment]
> # Do not manage Picture-in-picture windows
>   - command: "ignore"
>     match_title: "[Pp]icture.in.[Pp]icture"
>     match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"
> ```

Nice solution, works with Brave too. IMHO this would fit in the readme

**Comment by AmineDjeghri** [comment]
thanks ! It works for Brave too. 
And if you use another language in you OS (for me it's french), you need to match the name if the window like : 
```
  - command: "ignore"
    match_title: "Image en incrustation"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"
 ```

**Comment by AmineDjeghri** [comment]
i 

> HO this would fit in the readme

I created a pull request #480

**Comment by SirTenzin** [comment]
For future Arc browser users who are facing issues with Arc browsers' PiP window not being ignored properly, here is the following snippet to add to your config file:

```
window_rules:
  - commands: ['ignore']
    match:
      - window_title: { equals: 'Arc picture in picture' }
```

Enjoy :)

**Comment by lazerphp** [comment]
In my case, to fix this i needed to write title in my own language in ignore rule.
