### ISSUE TITLE
Maximized screen when changing workspace

### ISSUE THREAD

**Issue by jaymorelli96** [glazerdesktop/GlazeWM#483]
Let's say I am in workspace 2 with 3 applications. If I decide to toggle maximize for a given application whenever I move to a different workspace the application in workspace 2 doesn't stay maximized. It is pretty annoying, not sure if it is a bug locally, a setting that can be configured or if this is the default behavior

**Comment by Fuann-Kinoko** [comment]
it is fixed in #421, but unfortunately there haven't been a new release. You can try to build it in latest `develop` branch

**Comment by jaymorelli96** [comment]
Thanks, it works 😄 Do you know of any plans for a monocle layout?
