### ISSUE TITLE
Tray/Task Support on Bar

### ISSUE THREAD

**Issue by M1ch431** [glazerdesktop/GlazeWM#88]
Title 🙂

Maybe this repo could be useful in implementing this? -

[https://github.com/cairoshell/ManagedShell](https://github.com/cairoshell/ManagedShell)

**Comment by lars-berger** [comment]
Hey, I really appreciate the link!

Thought that adding tray support to the bar would be completely infeasible, but this actually makes it doable. From a quick glance, the documentation also looks solid. Adding some sort of integration with `ManagedShell` would be a great addition down the line 👍

**Comment by lzhecz** [comment]
I found on github program that uses that library to implement dock on windows. I use it as temporary solution as a floating tray over glazewm bar. Works for me. 

https://github.com/ze0nni/ProtoDock


A little bit changed settings and skin and how it looks on my desktop:

![GlazeWM_x64_1 9](https://user-images.githubusercontent.com/34045305/205294476-c50b9cdc-3a62-4a02-b0c4-ae45e6c60733.png)
